FROM ruby:2.5.1-alpine3.7
MAINTAINER Vitor Pontes

RUN apk update && apk add nodejs build-base libxml2-dev libxslt-dev \
    sqlite sqlite-dev sqlite-libs \
    postgresql postgresql-dev postgresql-libs

ENV APP_HOME /app/user
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ADD ./Gemfile $APP_HOME/
ADD ./Gemfile.lock $APP_HOME/
RUN bundle install

ADD . $APP_HOME
CMD bundle exec puma -C config/puma.rb
